version: '3'

services:
    backend:
        container_name: task_manager
        restart: always
        build: .
        ports: 
          - "4000:4000"
        links:
          - mongo
        
    mongo:
        container_name: mongodatabase
        image: mongo
        ports: 
            - "27018:27017"